
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-app
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dummy-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dummy-app
    spec:
      containers:
      - name: dummy-app
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "700m"
            memory: "800Mi"
          requests:
            cpu: "500m"
            memory: "600Mi"